<a href="https://colab.research.google.com/github/Manish-k723/100-days-of-ML/blob/main/Day_54_SGDRegressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np
import seaborn as sns
import pandas as pd

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [30]:
X,y = load_diabetes(return_X_y = True)

In [31]:
X_train,X_val,y_train,y_val =train_test_split(X,y, test_size = 0.2, random_state = 12)

In [32]:
model = LinearRegression()

In [33]:
model.fit(X_train,y_train)
model.coef_, model.intercept_

(array([ -53.9271644 , -228.97924355,  535.29346579,  350.36740549,
        -736.21177951,  427.42399227,   94.8028264 ,  184.23951707,
         721.91554934,  115.46088346]),
 152.89572568540441)

In [34]:
pred = model.predict(X_val)
r2_score(pred, y_val)

-0.0631809800729588

In [11]:
class SGDRegressor:
  
  def __init__(self, learning_rate = 0.01, epochs = 100):
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.coef_ = None
    self.intercept_ = None

  def fit(self, X_train, y_train):
    self.intercept_ = 0
    self.coef_ = np.ones(X_train.shape[1])
    
    for i in range(self.epochs):
      for j in range(X_train.shape[0]):
        idx = np.random.randint(0,X_train.shape[0])
        y_hat = np.dot(X_train[idx], self.coef_) + self.intercept_

        intercept_der = -2*(y_train[idx] - y_hat)
        self.intercept_ = self.intercept_ - self.learning_rate * intercept_der

        coef_der = -2*np.dot((y_train[idx] - y_hat),X_train[idx])
        self.coef_ = self.coef_ - self.learning_rate * coef_der
    print(self.coef_, self.intercept_)

  def predict(self, X_test):
    return np.dot(X_test, self.coef_) + self.intercept_

In [20]:
sgd = SGDRegressor(learning_rate = 0.001, epochs = 50)

In [21]:
sgd.fit(X_train, y_train)

[ 21.94055912  -0.5671101   71.43271628  54.0549789   21.30954098
  16.33120977 -43.42768757  49.38274883  64.70039308  45.34760632] 157.81769110167414


In [22]:
y_pred = sgd.predict(X_val)
r2_score(y_pred, y_val)

-27.594386364327804

In [35]:
from sklearn.linear_model import SGDRegressor

In [42]:
model = SGDRegressor(max_iter = 2000)

In [43]:
model.fit(X_train,y_train)
model.coef_, model.intercept_

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:1548: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


(array([  22.67217319,  -53.69190814,  345.04622018,  233.74854409,
          21.29479489,  -10.97677559, -184.69494653,  155.64939842,
         276.61662629,  153.85861272]),
 array([153.25620049]))

In [44]:
pred = model.predict(X_val)
r2_score(pred, y_val)

-0.9881086550940643