<a href="https://colab.research.google.com/github/Manish-k723/100-days-of-ML/blob/main/Day_55_MBGDRegressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
import seaborn as sns
import pandas as pd

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [23]:
X,y = load_diabetes(return_X_y = True)

In [24]:
X_train,X_val,y_train,y_val =train_test_split(X,y, test_size = 0.2, random_state = 42)

In [25]:
model = LinearRegression()

In [26]:
model.fit(X_train,y_train)
model.coef_, model.intercept_

(array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
        -931.48884588,  518.06227698,  163.41998299,  275.31790158,
         736.1988589 ,   48.67065743]),
 151.34560453985995)

In [27]:
pred = model.predict(X_val)
r2_score(pred, y_val)

0.00690491583216335

In [28]:
import random
class MBGDRegressor:
  def __init__(self, batch_size = 25, learning_rate = 0.01, epochs = 100):
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.coef_ = None
    self.intercept_ = None
    self.batch_size = batch_size

  def fit(self, X_train, y_train):
    self.intercept_ = 0
    self.coef_ = np.ones(X_train.shape[1])
    
    for i in range(self.epochs):
      for j in range(X_train.shape[0]//self.batch_size):
        #generating random batch of indexes
        idx = random.sample(range(X_train.shape[0]), self.batch_size)

        #calculating predicted values
        y_hat = np.dot(X_train[idx], self.coef_) + self.intercept_
        #calculating derivative of intercept/slope
        intercept_der = -2*np.mean(y_train[idx] - y_hat)
        #calculating intercept
        self.intercept_ = self.intercept_ - self.learning_rate * intercept_der

        #calculating coeficient derivatives/slope
        coef_der = -2*np.dot((y_train[idx] - y_hat),X_train[idx])
        # calculating coefficients derivates
        self.coef_ = self.coef_ - self.learning_rate * coef_der
    print(self.coef_, self.intercept_)

  def predict(self, X_test):
    return np.dot(X_test, self.coef_) + self.intercept_

In [53]:
mbgd = MBGDRegressor(batch_size = X_train.shape[0]//10,learning_rate = 0.05, epochs = 100)

In [54]:
mbgd.fit(X_train, y_train)

[  35.47155018 -249.89197068  556.82059936  350.12523144 -107.10056192
 -100.50766944 -201.08062024  150.14629873  436.61111074   41.0154389 ] 155.98453292524252


In [55]:
y_pred = mbgd.predict(X_val)
r2_score(y_pred, y_val)

-0.01156798097017897

In [57]:
from sklearn.linear_model import SGDRegressor

In [58]:
model = SGDRegressor(learning_rate = 'constant')

In [59]:
batch_size = 35

for i in range(100):

  idx = random.sample(range(X_train.shape[0]), batch_size)
  model.partial_fit(X_train[idx],y_train[idx])

In [60]:
model.coef_, model.intercept_

(array([ 20.19451208,   0.38924829,  68.79303834,  52.84474461,
         21.25603952,  15.04932517, -40.21556085,  45.50186671,
         62.68683161,  43.35248848]),
 array([143.25359369]))

In [61]:
r2_score(model.predict(X_val),y_val)

-29.992775369267207